<?php
declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    protected $fillable = ['name'];

    protected function getArrayableAttributes()
    {
        foreach ($this->attributes as $key => $value) {
            $this->attributes['name'] = null;
        }

        return $this->getArrayableItems($this->attributes);
    }

    public function __get($key)
    {
        if ($key == 'name') {
            return null;
        }

        return parent::getAttribute($key); // TODO: Change the autogenerated stub
    }

}
